import Head from 'next/head'
import Image from 'next/image'

import { Layout, Menu, Breadcrumb } from 'antd';
import { Card, Col, Row } from 'antd';

const { Content } = Layout;


export default function Home({categories}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Content style={{ padding: '0 50px' }}>
          <div className="site-card-wrapper">
              ejemplo
          </div>
          </Content>
    </div>
  )
}
